name: Build Test

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    name: build test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: root package install
        run: npm ci
      - name: shared package install && build 
        run: cd packages/shared && npm ci && npm run build
      - name: client package install && build
        run: cd client && npm ci && npm run build
      - name: server package install && build
        run: cd server && npm ci && npm run build
