name: eslint

on:
  push:
    branches: [master]
  pull_request:

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: root package install
        run: npm ci
      - name: shared package install && eslint
        run: cd packages/shared && npm ci && npm run build && npx eslint ./src
      - name: client package install && eslint
        run: cd client && npm ci && npx eslint ./src
      - name: server package install && eslint
        run: cd server && npm ci && npx eslint ./src
